### ISSUE TITLE
Broken test run with NODE_ENV issue

### ISSUE THREAD

**Issue by RIP21** [timarney/react-app-rewired#101]
This is what happened when I try to run `yarn test` or `npm test`.
The latest version of everything.
OS: Mac OS.
Latest node, npm and yarn.
Repo to reproduce the bug:
https://github.com/RIP21/no-env-imports-tests
(repo name is not correlated with bug, I just used my old one)
```
/Users/andriilos/Projects/Others/no-env-imports-tests/node_modules/react-scripts/config/env.js:22
  throw new Error(
  ^

Error: The NODE_ENV environment variable is required but was not specified.
    at Object.<anonymous> (/Users/andriilos/Projects/Others/no-env-imports-tests/node_modules/react-scripts/config/env.js:22:9)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andriilos/Projects/Others/no-env-imports-tests/node_modules/react-app-rewired/scripts/test.js:5:1)
    at Module._compile (module.js:573:30)
```

**Comment by RIP21** [comment]
Oh. I see that it's already fixed in this PR.
https://github.com/timarney/react-app-rewired/pull/99
Please merge, test and close this if it will fix it :)

**Comment by timarney** [comment]
@RIP21  react-app-rewired@1.3.0

**Comment by timarney** [comment]
@RIP21 did the latest version fix your issue?

**Comment by RIP21** [comment]
@timarney sorry. Yes, it did. I close that one.
