### ISSUE TITLE
app often stop working

### ISSUE THREAD

**Issue by didmehh** [timarney/react-app-rewired#112]
Hi guys. there have some error.
I don't known why. Because this package?
1. Terminal errors
```shell
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/issue/.npm/_logs/2017-10-12T08_14_55_071Z-debug.log
```
2. Log info
```shell
# tail -f log
0 info it worked if it ends with ok
1 verbose cli [ '/home/issue/.nvm/versions/node/v6.1.0/bin/node',
1 verbose cli   '/home/issue/.nvm/versions/node/v6.1.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle project@0.1.0~prestart: project@0.1.0
6 silly lifecycle project@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle project@0.1.0~start: project@0.1.0
8 verbose lifecycle project@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle project@0.1.0~start: PATH: /home/issue/.nvm/versions/node/v6.1.0/lib/node_modules/npm/bin/node-gyp-bin:/project/node_modules/.bin:/home/issue/.nvm/versions/node/v6.1.0/bin:/home/issue/.rvm/gems/ruby-2.3.1/bin:/home/issue/.rvm/gems/ruby-2.3.1@global/bin:/home/issue/.rvm/rubies/ruby-2.3.1/bin:/home/issue/bin:/home/issue/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/issue/.rvm/bin:/home/issue/.rvm/bin
10 verbose lifecycle project@0.1.0~start: CWD: /project
11 silly lifecycle project@0.1.0~start: Args: [ '-c', 'react-app-rewired start' ]
12 silly lifecycle project@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle project@0.1.0~start: Failed to exec start script
14 verbose stack Error: project@0.1.0 start: `react-app-rewired start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/issue/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/issue/.nvm/versions/node/v6.1.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid project@0.1.0
16 verbose cwd /project
17 verbose Linux 4.10.0-33-generic
18 verbose argv "/home/issue/.nvm/versions/node/v6.1.0/bin/node" "/home/issue/.nvm/versions/node/v6.1.0/bin/npm" "start"
19 verbose node v6.1.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error project@0.1.0 start: `react-app-rewired start`
23 error Exit status 1
24 error Failed at the project@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```
3. package.json
```shell
{
  "name": "project",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "antd": "^2.13.4",
    "react": "15.6.1",
    "react-dom": "15.6.1",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.14"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.6.0",
    "react-app-rewired": "^1.3.1"
  }
}
```

4. config-overrides.js
```es6
const { injectBabelPlugin } = require('react-app-rewired');

module.exports = function override(config, env) {
  config = injectBabelPlugin(['import', { libraryName: 'antd', style: 'css' }], config);
  return config;
};

```

**Comment by timarney** [comment]
Is your project easy to test without the rewire (react-scripts start)?  Might help to narrow things down a bit.

**Comment by didmehh** [comment]
i was use the antd. I can't to eject project.
But i think that about`npm` version .
current version was 3.8.6.The old version was 4.x.x.
Please give me some times to find this issue.
My company computer was 4.x.x version. My was 3.8.6 version.

**Comment by didmehh** [comment]
I think that because of computer.
In the last week, my company's computer had a little of problem.
I'm sorry to bother.

**Comment by timarney** [comment]
Okay no worries.

**Comment by parthmakadiya12** [comment]
First Check `node --version` and `npm --version`
I had the same issue .I tried it by updating node and npm then 
The actual issue is solved by these three code

`npm uninstall watchman -g`
`brew install watchman`
`npm start from project directory
`

It's all connected with version of watchman that I am using .(if you have same error try checking versions )
Error Reference:- [](https://pastebin.com/CvF8bNm0)

**Comment by MatthewDevelop** [comment]
how did you solve this issue?
