### ISSUE TITLE
React Rewire Less Error 'Cannot read property 'unshift' of undefined'

### ISSUE THREAD

**Issue by syedsaadh** [timarney/react-app-rewired#136]
Getting Error while 
>`react-app-rewired start`

` X:\Development\Web\Sandbox\camelot\node_modules\react-app-rewire-less\index.js:45
    config.module.rules[1].oneOf.unshift(lessRules); `

`TypeError: Cannot read property 'unshift' of undefined
    at X:\Development\Web\Sandbox\camelot\node_modules\react-app-rewire-less\index.js:45:33
    at override (X:\Development\Web\Sandbox\camelot\config-overrides.js:6:12)
    at Object.<anonymous> (X:\Development\Web\Sandbox\camelot\node_modules\react-app-rewired\scripts\start.js:16:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3`

**Comment by syedsaadh** [comment]
thanks @dawnmist
