### ISSUE TITLE
breaks with NODE_ENV=production

### ISSUE THREAD

**Issue by OrenSchwartz** [timarney/react-app-rewired#268]
works as expected without setting the NODE_ENV as such.

version 1.5.2 but tested on latest versions as well.
using create react app with the basic implementation of config-overrides.js which only does 
const rewireLess = require("react-app-rewire-less");
  config = rewireLess.withLoaderOptions({
    javascriptEnabled: true ,
    modifyVars: { 
        "@layout-header-background": DEFAULT_COLOR,
        "@primary-color": DEFAULT_COLOR,
     },
  })(config, env);

Output is:
TypeError: cssRules.loader is not iterable
    at /Users/orenschwartz/Projects/vn-web-app/node_modules/react-app-rewire-less/index.js:28:23
    at Object.override [as webpack] (/Users/orenschwartz/Projects/vn-web-app/config-overrides.js:35:5)
    at Object.<anonymous> (/Users/orenschwartz/Projects/vn-web-app/node_modules/react-app-rewired/scripts/start.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

**Comment by aprather51** [comment]
having same issues with react-sass

```
2018-07-09T13:13:31.209270+00:00 app[web.1]: [1] > react-app-rewired start
2018-07-09T13:13:31.209264+00:00 app[web.1]: [1]
2018-07-09T13:13:31.209272+00:00 app[web.1]: [1]
2018-07-09T13:13:32.659391+00:00 app[web.1]: [1] /app/client/node_modules/react-app-rewire-scss/index.js:23
2018-07-09T13:13:32.659405+00:00 app[web.1]: [1]                                use: [...cssRules.loader, { loader: 'sass-loader', options: sassLoaderOptions }],
2018-07-09T13:13:32.659408+00:00 app[web.1]: [1]                                                  ^
2018-07-09T13:13:32.659411+00:00 app[web.1]: [1]
2018-07-09T13:13:32.659413+00:00 app[web.1]: [1] TypeError: cssRules.loader is not iterable
2018-07-09T13:13:32.659415+00:00 app[web.1]: [1]     at /app/client/node_modules/react-app-rewire-scss/index.js:23:23
2018-07-09T13:13:32.659416+00:00 app[web.1]: [1]     at Object.override [as webpack] (/app/client/config-overrides.js:4:11)
2018-07-09T13:13:32.659419+00:00 app[web.1]: [1]     at Object.<anonymous> (/app/client/node_modules/react-app-rewired/scripts/start.js:13:13)
```

**Comment by timarney** [comment]
If you log out what cssRules.loader is in Dev and Prod do you get different results?

**Comment by joshuagish** [comment]
This is the output of cssRules in both dev and prod. You can see that loader is never set.
`
cssRules = {
  test: /\.css$/,
  use: [
    '(...ProjectPath)/node_modules/style-loader/index.js',
    {
      loader: '(...ProjectPath)/node_modules/css-loader/index.js',
      options: [Object]
    },
    {
      loader: '(...ProjectPath)/node_modules/postcss-loader/lib/index.js',
      options: [Object]
    }
  ]
}
`

**Comment by timarney** [comment]
@OrenSchwartz curious if the workaround from @joshuagish fixes that issue?  That would help narrow things down a little.

**Comment by timarney** [comment]
Closing this.  If there's further feedback can re-open.

**Comment by snadn** [comment]
@timarney I also encountered the same problem, and the workaround from @joshuagish fixes this issue

**Comment by albertpai** [comment]
Hi, I am using 'react-app-rewired' and 'react-app-rewire-less' to build my app, and I had the same problem when deploying it to Heroku. Joshuagish's workaround seems to require changing a file (index.js in react-app-rewire-less) in node_module, but changing anything in node_module means it will be updated whenever npm is updated. My temporary solution is setting `NODE_ENV` to `DEV` to bypass the bug, but it would not be a good solution in the long term. Since the problem persists, could you please reopen this issue? Thanks!

**Comment by OrenSchwartz** [comment]
> @OrenSchwartz curious if the workaround from @joshuagish fixes that issue? That would help narrow things down a little.

Seems to work. Thanks!

**Comment by audifaxdev** [comment]
This is still happening. What's the workaround, the link is dead?

**Comment by dawnmist** [comment]
@audifaxdev I think it was the contents of the merge request: https://github.com/timarney/react-app-rewired/pull/300/files (specifically the `|| cssLoader.use` fallback on line 21).
Issue being that Webpack changed from using the `loader` field to using the `use` field instead, and the webpack config setup by create-react-app started using the new `use` field in the production configuration.

The merge request was merged, and should be part of any version later than 2.1.3.

**Comment by tonisives** [comment]
This still happens in github actions. 

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: build
        run: yarn run build
```

```
Run yarn run build
yarn run v1.22.1[7](https://github.com/tonisives/arbuna-front-end/runs/5524911416?check_suite_focus=true#step:4:7)
$ react-app-rewired build
/bin/sh: 1: react-app-rewired: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 127.
```

If I remove the NODE_ENV variable form yaml the build succeeds.
I am using `"react-app-rewired": "^2.2.1"`

Does anyone know how to fix it?


Locally it's fine.

**Comment by dawnmist** [comment]
@tonisives By setting the NODE_ENV to production for the yarn install step, you're actually saying _"don't install the devDependencies to compile the application with"_.

You _need_ those devDependencies installed, or you won't be able to run `yarn build`. React-app-rewired is usually listed as a devDependency (since it's used for compiling, but not for the deployed site after the site has been compiled), hence by not installing the devDependencies on the build machine you wouldn't have react-app-rewired installed to be able to compile with.

Create-react-app locks any build created to `NODE_ENV=production` anyway - so you actually shouldn't need to be setting the NODE_ENV variable in the job that you've posted at all. If you do need it elsewhere, try moving the environment variable so that it is _only_ set for the particular parts of the step that actually need it. In particular, do _not_ set it to production for installing dependencies immediately prior to building.

**Comment by tonisives** [comment]
@dawnmist Thank you for your thorough answer. I now realise I didn't need to add this env variable at all, because this is used in the build anyway.
