### ISSUE TITLE
can't find webpack.config.dev

### ISSUE THREAD

**Issue by SagaciousLittle** [timarney/react-app-rewired#345]
I built a new application with the create-react-app scaffolding. I want to use react-app-rewired in my project, but when I execute react-app-rewired start, I reported the following error. Where is the problem please?
    Problem:
    Cannot find module 'myprojectpath\node_modules\react-scripts/config/webpack.config.dev'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (myprojectpath\node_modules\react-app-rewired\scripts\start.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    error Command failed with exit code 1.

**Comment by tyde7** [comment]
I have this problem too...

**Comment by Aliceco** [comment]
把 react-scripts 包版本降低
"react-app-rewired": "^1.6.2",
 "react-scripts": "^1.0.14",

**Comment by AndyOGo** [comment]
@SagaciousLittle 
Just switch to CRACO JS (crafted for CRA V2)
https://github.com/sharegate/craco

**Comment by wuxiii** [comment]
same to me

**Comment by xnng** [comment]
This is the problem with react-scripts 2.1.2, which happened four days ago.

![image](https://user-images.githubusercontent.com/38936252/50477647-2d726a80-0a08-11e9-98c0-91a2e0de3b4b.png)

This is the quickest way to solve the problem：

```bash
$ yarn add react-scripts@2.1.1
```

or 

```bash
$ npm install react-scripts@2.1.1 --save
```

**Comment by wuxiii** [comment]
> This is the problem with react-scripts 2.1.2, which happened four days ago.
> 
> ![image](https://user-images.githubusercontent.com/38936252/50477647-2d726a80-0a08-11e9-98c0-91a2e0de3b4b.png)
> 
> This is the quickest way to solve the problem：
> 
> ```shell
> $ yarn add react-scripts@2.1.1
> ```
> 
> or
> 
> ```shell
> $ npm install react-scripts@2.1.1 --save
> ```

Thanks, it is a Version issue

**Comment by SagaciousLittle** [comment]
> 这是四天前发生的react-scripts 2.1.2的问题。
> 
> ![图片](https://user-images.githubusercontent.com/38936252/50477647-2d726a80-0a08-11e9-98c0-91a2e0de3b4b.png)
> 
> 这是解决问题的最快方法：
> 
> ```shell
> $ yarn add react-scripts@2.1.1
> ```
> 
> 要么
> 
> ```shell
> $ npm install react-scripts@2.1.1 --save
> ```

thanks
