### ISSUE TITLE
npm test fail on create react app: While processing preset: "./node_modules/babel-preset-react-app/index.js"

### ISSUE THREAD

**Issue by kopax** [timarney/react-app-rewired#351]
I am using create-react-app and `react-scripts@v2.1.3`.

I have the following output when I run my tests:

     FAIL  src/containers/HomePage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/SolutionsPage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/MethodologiesPage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/BenefitsPage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/ContactPage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/tests/App.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/Footer/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/HomePage/components/Benefits/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/NotFoundPage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/NavBar/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/FranchisePage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
     FAIL  src/containers/CustomersPage/tests/index.test.js
      ● Test suite failed to run
    
        ReferenceError: [BABEL]/www/src/setupTests.js: Unknown option:/www/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    
        A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    
        Invalid:
          `{ presets: [{option: value}] }`
        Valid:
          `{ presets: [['presetName', {option: value}]] }`
    
        For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/dka/workspace/repo.com/project/www/node_modules/babel-preset-react-app/index.js")
    
          at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
          at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
              at Array.map (<anonymous>)
          at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
          at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
          at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
          at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
          at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
    
    Test Suites: 12 failed, 12 total
    Tests:       0 total
    Snapshots:   0 total
    Time:        2.312s
    Ran all test suites related to changed files.

We use `react-app-rewire@2.0.2`, this is what we have in our `config-overrides.js`:

    const rewireDefinePlugin = require('@yeutech-lab/react-app-rewire-define-plugin');
    module.exports = {
      webpack: (config, env) => {
        config = rewireDefinePlugin(config, env, {
          'process.env.VERSION': JSON.stringify(require('./package.json').version),
          'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
          'process.env.GA_TRACKING_ID': JSON.stringify(process.env.GA_TRACKING_ID),
        });
        return config;
      },
      jest: (config) => {
        config.testResultsProcessor = 'jest-sonar-reporter';
        return config;
      },
    };

And our `.babelrc` (read by react-app-rewired):

```json
{
  "plugins": [
    "babel-plugin-styled-components",
    "babel-plugin-array-includes"
  ]
}
```

Logs: https://paste.gnome.org/pgoykft7g

How can I fix this error? Thanks in advance.

**Comment by tleh** [comment]
We had the same problem and were able to solve it with [this](https://github.com/timarney/react-app-rewired/issues/348#issuecomment-452199363) solution.

react-app-rewire removed all the helper functions. Replace them with functions from customize-cra.
The post is mainly about injectBabelPlugin, but the solution is for all helper functions

**Comment by kopax** [comment]
@leifdejong to be honest, we solved this and I cannot remember if it was a rollback or a different error. 
Unfortunately, I work on many packages everyday, it makes it harder to remember.

I prefer to close and if I see again this error, I will try to proceed to analysis using both answers.

Thanks, both of you.
