### ISSUE TITLE
`npm run eject` throws a error

### ISSUE THREAD

**Issue by happystory** [timarney/react-app-rewired#369]
```
$ react-app-rewired eject
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../scripts/eject'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at Object.<anonymous> (/Users/liuyao/Test/react-example/node_modules/react-app-rewired/bin/index.js:19:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The error should be handled.

**Comment by dawnmist** [comment]
React-app-rewired should only be used with `start`, `build` and `test`. It should **not** be used with `eject`. This is why the `eject` script is _not_ listed in the set of scripts to update in the Readme, and why the only place within the Readme where the `eject` script _is_ listed shows that it should be _left_ as `react-scripts eject` instead of being changed. You can only run the `eject` script on a project once - and it makes no sense to be rewiring it as the end result of running eject is that your project now has its own personal set of configuration files.

After using `eject`, react-app-rewired is no longer required. The whole point of react-app-rewired is to provide the ability to tweak the configuration _without_ having to eject. After ejecting, the configuration is added to your project directly, and you have full and permanent control of both the content of the configuration scripts and the responsibility for maintaining them yourself.
