### ISSUE TITLE
Command failed to start with script version typescript

### ISSUE THREAD

**Issue by arpitprod** [timarney/react-app-rewired#486]
I'm moving my project from javascript to typescript and I changed these scripts commands in package.json file

> {
  "scripts": {
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
    "build": "react-app-rewired build --scripts-version react-scripts-ts",
    "test": "react-app-rewired test --scripts-version react-scripts-ts",
    "eject": "react-scripts eject"
  }
}

When I run `yarn start` then it's breaking with this error message

> yarn run v1.22.5
$ react-app-rewired start --scripts-version react-scripts-ts
internal/modules/cjs/loader.js:895
  throw err;
  ^
Error: Cannot find module 'react-scripts-ts/package.json'
Require stack:
 /Users/abc/Documents/project/node_modules/react-app-rewired/scripts/utils/paths.js
 /Users/abc/Documents/project/node_modules/react-app-rewired/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.<anonymous> (/Users/abc/Documents/project/node_modules/react-app-rewired/scripts/utils/paths.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/abc/Documents/project/node_modules/react-app-rewired/scripts/start.js:5:27) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/abc/Documents/project/node_modules/react-app-rewired/scripts/utils/paths.js',
    '/Users/abc/Documents/project/node_modules/react-app-rewired/scripts/start.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

These are related versions

> "customize-cra": "^1.0.0",
    "react": "^16.13.1",
    "react-app-rewired": "^2.1.6",
    "react-dom": "^16.13.1",
    "react-scripts": "^3.4.3",
    "typescript": "^4.0.2",
 

Please tell what I'm doing wrong

**Comment by arpitprod** [comment]
I found solution here #478 
Please update documents
