### ISSUE TITLE
`overrideFn is not a function` when trying to run `react-app-rewired start` with react-scripts 1.0.13

### ISSUE THREAD

**Issue by icopp** [timarney/react-app-rewired#97]
```
TypeError: overrideFn is not a function
    at Object.<anonymous> (<PATH>/node_modules/react-app-rewired/scripts/build.js:19:57)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

I took a look in `node_modules/react-scripts/config/paths.js` and it looks like there's no `webpack` key in the exported object, which is what seems to make the bit in `react-app-rewired` defining `overrideFn` end up undefined.

**Comment by Guria** [comment]
Please share your config-overrides.js file

**Comment by icopp** [comment]
It does the same thing with as simple as I can make it:

```
// config-overrides.js
module.export = function override(config, env) {
  return config;
};
```

**Comment by Guria** [comment]
replace `module.export` with `module.exports` and try it again

**Comment by icopp** [comment]
Ah, heck, that was it. Sorry!
